"use client";

import { Box, Button, TextField, Typography } from "@mui/material";
import { Formik } from "formik";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

import { useTodoContext } from "../context/todoContext";

function Login() {
  const { login } = useTodoContext();
  const router = useRouter();
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  const onSubmit = async () => {
    if (!email || !password) {
      toast.error("Invaild Credentials");
    }
    const userData = await login({
      email,
      password,
    });

    console.log(userData);
    if (userData.status == 200) {
      router.push("/");
      toast.success("Logged-In Successfully");
    } else {
      toast.error("Invaild Credentials");
      console.log(userData);
      return;
    }
  };

  return (
    <>
      <Head>
        <title>Login Todo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Formik>
        <Box
          height={"100vh"}
          width={"100vw"}
          display={"flex"}
          alignItems={"center"}
          justifyContent={"center"}
        >
          <form>
            <Typography
              align="center"
              variant="h5"
              color={"#667780"}
              fontWeight={"bold"}
              marginBottom={"1rem"}
            >
              Login To the Task Tracker
            </Typography>
            <Box display="grid" gap="1rem" width="500px" margin={"auto"}>
              <TextField
                label="Email"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
              />
              <TextField
                label="Password"
                type="password"
                name="password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
              />
              {/* BUTTONS */}
              <Box>
                <Button
                  fullWidth
                  sx={{
                    backgroundColor: "#8500FA",
                    color: "#FFFFFF",
                    "&:hover": { color: "#8500FA" },
                  }}
                  onClick={onSubmit}
                >
                  LOGIN
                </Button>

                <Box sx={{ display: "flex", gap: ".5rem", marginTop: "1rem" }}>
                  <Typography>Don't have an account?</Typography>

                  <Typography
                    onClick={() => {
                      router.push("/register");
                    }}
                    sx={{
                      color: "#8500FA",
                      cursor: "pointer",
                    }}
                  >
                    Sign Up here.
                  </Typography>
                </Box>
              </Box>
            </Box>
          </form>
        </Box>
      </Formik>
    </>
  );
}

export default Login;
