"use client";

import React from "react";
import { Box, Button, TextField, Typography } from "@mui/material";
import { Formik } from "formik";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";

import { toast } from "react-toastify";
import { useTodoContext } from "@/context/todoContext";

const Register = () => {
  const { register } = useTodoContext();
  const router = useRouter();
  const [firstname, setFirstname] = useState("");
  const [lastname, setLastname] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  const onSubmit = async (e) => {
    e.preventDefault();
    console.log({ firstname, lastname, email, password });
    try {
      const userData = await register({
        firstname,
        lastname,
        email,
        password,
      });
      console.log(userData);
      if (userData && userData.status == 200) {
        router.push("/login");
        toast.success("Registration Successful!");
      } else {
        toast.success("Registration Failed!");
        console.log(userData);
      }
    } catch (error) {
      console.log("Error occurred during registration:", error);
    }
  };

  return (
    <>
      <Head>
        <title>Register Todo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Formik>
        <Box
          height={"100vh"}
          width={"100vw"}
          display={"flex"}
          alignItems={"center"}
          justifyContent={"center"}
        >
          <form>
            <Typography
              align="center"
              variant="h5"
              color={"#667780"}
              fontWeight={"bold"}
              marginBottom={"1rem"}
            >
              Register To the Task Tracker
            </Typography>
            <Box display="grid" gap="1rem" width="500px">
              <TextField
                type="text"
                label="First Name"
                // name='firstName'
                fullWidth
                value={firstname}
                onChange={(e) => setFirstname(e.target.value)}
              />
              <TextField
                type="text"
                label="Last Name"
                // name='lastName'
                fullWidth
                value={lastname}
                onChange={(e) => setLastname(e.target.value)}
              />
              <TextField
                type="email"
                label="Email"
                // name='email'
                value={email}
                onChange={(e) => setEmail(e.target.value)}
              />
              <TextField
                label="Password"
                type="password"
                // name='password'
                value={password}
                onChange={(e) => setPassword(e.target.value)}
              />
              {/* BUTTONS */}
              <Box>
                <Button
                  fullWidth
                  sx={{
                    backgroundColor: "#8500FA",
                    color: "#FFFFFF",
                    "&:hover": { color: "#8500FA" },
                  }}
                  onClick={onSubmit}
                >
                  REGISTER
                </Button>

                <Box sx={{ display: "flex", gap: ".5rem", marginTop: "1rem" }}>
                  <Typography>Don't have an account?</Typography>
                  <Typography
                    onClick={() => {
                      router.push("/login");
                    }}
                    sx={{
                      color: "#8500FA",
                      cursor: "pointer",
                    }}
                  >
                    Log In here.
                  </Typography>
                </Box>
              </Box>
            </Box>
          </form>
        </Box>
      </Formik>
    </>
  );
};

export default Register;
